apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-api-17801
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-api-17801
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
